### ISSUE TITLE
Test on indoor_flying3 fails

### ISSUE THREAD

**Issue by WilliamHBW** [danqu130/DCEIFlow#4]
test on indoor_flying3 fails and here is the error information.

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/mmspg/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/mmspg/Desktop/DCEIFlow/main.py", line 229, in test
    scores = evaluates(args, model, test_sets, test_setnames, metric_fun, logger=logger)
  File "/home/mmspg/Desktop/DCEIFlow/evaluate.py", line 54, in evaluates
    metric = evaluate(args, model, val_loader, name, metric_fun, logger=logger)
  File "/home/mmspg/Desktop/DCEIFlow/evaluate.py", line 80, in evaluate
    for index, batch in enumerate(dataloader):
  File "/home/mmspg/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/mmspg/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/mmspg/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/mmspg/anaconda3/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mmspg/anaconda3/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mmspg/anaconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mmspg/anaconda3/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mmspg/Desktop/DCEIFlow/utils/datasets/MVSEC.py", line 182, in __getitem__
    final_flow = generate_corresponding_gt_flow(flows, flows_ts, image1_ts, next_ts)
  File "/home/mmspg/Desktop/DCEIFlow/utils/datasets/MVSEC_utils.py", line 102, in generate_corresponding_gt_flow
    assert flow_length == len(flows_ts) - 1
AssertionError

Can someone help to take a look at this? Thank you,

**Comment by danqu130** [comment]
I just ran a test and it works fine on all five sequences of MVSEC. If you are only having this problem on the indoor_flying3 sequence, consider checking the downloaded data file for corruption.

```
❯ md5sum indoor_flying3_gt.hdf5 indoor_flying3_data.hdf5
027e29e548feb494deb1ceeee1a31112  indoor_flying3_gt.hdf5
bac26bf1c883b3cceee11ca91428f659  indoor_flying3_data.hdf5
```

**Comment by danqu130** [comment]
I'm closing this issue now, if there are any further problems please feel free to post them.
